# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class BatterStat(scrapy.Item):
    player_id = scrapy.Field()
    name = scrapy.Field()
    normalized_player_name = scrapy.Field()
    team = scrapy.Field()
    batorder = scrapy.Field()
    pos = scrapy.Field()
    dh = scrapy.Field()
    ab = scrapy.Field()
    pa = scrapy.Field()
    ops = scrapy.Field()
    babip = scrapy.Field()
    bb_k = scrapy.Field()
    wrc_plus = scrapy.Field()
    woba = scrapy.Field()
    barrel_percent = scrapy.Field()
    hard_hit = scrapy.Field()
    ev = scrapy.Field()
    iso = scrapy.Field()
    gb_fb = scrapy.Field()
    baserunning = scrapy.Field()
    wraa = scrapy.Field()
    wpa = scrapy.Field()
    scraped_at = scrapy.Field()
    date = scrapy.Field()
    season = scrapy.Field() 

class PitcherStat(scrapy.Item):
    player_id = scrapy.Field()
    name = scrapy.Field()
    normalized_player_name = scrapy.Field()
    team = scrapy.Field()
    dh = scrapy.Field()
    games = scrapy.Field()
    gs = scrapy.Field()
    era = scrapy.Field()
    ip = scrapy.Field()
    runs = scrapy.Field()
    babip = scrapy.Field()
    k_percent = scrapy.Field()
    bb_percent = scrapy.Field()
    barrel_percent = scrapy.Field()
    hard_hit = scrapy.Field()
    ev = scrapy.Field()
    hr_fb = scrapy.Field()
    siera = scrapy.Field()
    fip = scrapy.Field()
    stuff = scrapy.Field()
    ifbb = scrapy.Field()
    wpa = scrapy.Field()
    gmli = scrapy.Field()
    fa_percent = scrapy.Field()
    fc_percent = scrapy.Field()
    si_percent = scrapy.Field()
    fa_velo = scrapy.Field()
    fc_velo = scrapy.Field()
    si_velo = scrapy.Field()
    scraped_at = scrapy.Field()
    date = scrapy.Field()
    season = scrapy.Field()

class OddsItem(scrapy.Item):
    date = scrapy.Field()
    game_datetime = scrapy.Field()
    away_team = scrapy.Field()
    home_team = scrapy.Field()
    away_starter = scrapy.Field()
    home_starter = scrapy.Field()
    away_starter_normalized = scrapy.Field()
    home_starter_normalized = scrapy.Field()
    away_score = scrapy.Field()
    home_score = scrapy.Field()
    winner = scrapy.Field()
    sportsbook = scrapy.Field()
    away_opening_odds = scrapy.Field()
    home_opening_odds = scrapy.Field()
    away_current_odds = scrapy.Field()
    home_current_odds = scrapy.Field()
    season = scrapy.Field()

class LineupItem(scrapy.Item):
    date = scrapy.Field()
    dh = scrapy.Field()
    team_id = scrapy.Field()
    team = scrapy.Field()
    opposing_team_id = scrapy.Field()
    opposing_team = scrapy.Field()
    team_starter_id = scrapy.Field()
    opposing_starter_id = scrapy.Field()
    scraped_at = scrapy.Field()
    season = scrapy.Field()

class LineupPlayerItem(scrapy.Item):
    date = scrapy.Field()
    dh = scrapy.Field()
    team_id = scrapy.Field()
    team = scrapy.Field()
    opposing_team_id = scrapy.Field()
    opposing_team = scrapy.Field()
    player_id = scrapy.Field()
    position = scrapy.Field()
    batting_order = scrapy.Field()
    scraped_at = scrapy.Field()
    season = scrapy.Field()

class FRVItem(scrapy.Item):
    name = scrapy.Field()
    normalized_player_name = scrapy.Field()
    season = scrapy.Field()
    month = scrapy.Field()
    frv = scrapy.Field()
    total_innings = scrapy.Field()
    innings_C  = scrapy.Field()
    innings_1B = scrapy.Field()
    innings_2B = scrapy.Field()
    innings_3B = scrapy.Field()
    innings_SS = scrapy.Field()
    innings_LF = scrapy.Field()
    innings_CF = scrapy.Field()
    innings_RF = scrapy.Field()

class ParkFactorItem(scrapy.Item):
    venue_id = scrapy.Field()
    venue_name = scrapy.Field()
    season = scrapy.Field()
    park_factor = scrapy.Field()
    scraped_at = scrapy.Field()