# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class BatterStat(scrapy.Item):
    player_id = scrapy.Field()
    name = scrapy.Field()
    team = scrapy.Field()
    batorder = scrapy.Field()
    pos = scrapy.Field()
    dh = scrapy.Field()
    ab = scrapy.Field()
    pa = scrapy.Field()
    ops = scrapy.Field()
    babip = scrapy.Field()
    bb_k = scrapy.Field()
    wrc_plus = scrapy.Field()
    woba = scrapy.Field()
    barrel_percent = scrapy.Field()
    hard_hit = scrapy.Field()
    ev = scrapy.Field()
    iso = scrapy.Field()
    gb_fb = scrapy.Field()
    baserunning = scrapy.Field()
    wraa = scrapy.Field()
    wpa = scrapy.Field()
    scraped_at = scrapy.Field()
    date = scrapy.Field()

class PitcherStat(scrapy.Item):
    player_id = scrapy.Field()
    name = scrapy.Field()
    team = scrapy.Field()
    dh = scrapy.Field()
    games = scrapy.Field()
    gs = scrapy.Field()
    era = scrapy.Field()
    ip = scrapy.Field()
    runs = scrapy.Field()
    babip = scrapy.Field()
    k_percent = scrapy.Field()
    bb_percent = scrapy.Field()
    barrel_percent = scrapy.Field()
    hard_hit = scrapy.Field()
    ev = scrapy.Field()
    hr_fb = scrapy.Field()
    siera = scrapy.Field()
    fip = scrapy.Field()
    stuff = scrapy.Field()
    ifbb = scrapy.Field()
    wpa = scrapy.Field()
    gmli = scrapy.Field()
    scraped_at = scrapy.Field()
    date = scrapy.Field()

class OddsItem(scrapy.Item):
    date = scrapy.Field()
    away_team = scrapy.Field()
    home_team = scrapy.Field()
    away_starter = scrapy.Field()
    home_starter = scrapy.Field()
    away_score = scrapy.Field()
    home_score = scrapy.Field()
    winner = scrapy.Field()
    sportsbook = scrapy.Field()
    away_odds = scrapy.Field()
    home_odds = scrapy.Field()

class LineupItem(scrapy.Item):
    date = scrapy.Field()
    dh = scrapy.Field()
    team_id = scrapy.Field()
    opposing_team_id = scrapy.Field()
    team_starter_id = scrapy.Field()
    opposing_starter_id = scrapy.Field()
    scraped_at = scrapy.Field()

class LineupPlayerItem(scrapy.Item):
    date = scrapy.Field()
    dh = scrapy.Field()
    team_id = scrapy.Field()
    player_id = scrapy.Field()
    position = scrapy.Field()
    batting_order = scrapy.Field()
    scraped_at = scrapy.Field()